brs/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', include('components.users.urls')),
    path('admin/', admin.site.urls),
    path('book/', include('components.books.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

components/books/urls.py
from django.urls import path

from .views import (
    BookListView,
    BookDetailView,
    BookSearchView,
    BookCreateView,
    BookUpdateView,
    BookMarkReadView,
    BookFavoriteView,
    BookRequestBuyCreateView,
    BookRequestBuyListView,
    BookRequestBuyUpdateView,
    BookReviewCreateView,
    BookDeleteView,
    BookCategoryView,
    BookRatingCreateView
)

app_name = 'book'

urlpatterns = [
    path('', BookListView.as_view(), name='book-list'),
    path('<int:id>/', BookDetailView.as_view(), name='book-detail'),
    path('search/', BookSearchView.as_view(), name='book-search'),
    path('category/', BookCategoryView.as_view(), name='book-category'),
    path('add/', BookCreateView.as_view(), name='book-create'),
    path('<int:id>/edit/', BookUpdateView.as_view(), name='book-update'),
    path('<int:id>/del/', BookDeleteView.as_view(), name='book-delete'),
    path('<int:id>/mark/', BookMarkReadView.as_view(), name='book-mark'),
    path('<int:id>/like/', BookFavoriteView.as_view(), name='book-like'),
    path('add-request-buy/', BookRequestBuyCreateView.as_view(), name='add-request-buy'),
    path('list-request-buy/', BookRequestBuyListView.as_view(), name='list-request-buy'),
    path('edit-request-buy/<int:id>', BookRequestBuyUpdateView.as_view(), name='edit-request-buy'),
    path('<int:id>/review/', BookReviewCreateView.as_view(), name='book-review'),
    path('<int:id>/rating/', BookRatingCreateView.as_view(), name='book-rating'),
]

components/books/models.py
from django.core.validators import MaxValueValidator, MinValueValidator
from django.db import models
from django.contrib.postgres.fields import ArrayField

from components.users.models import User


class BookBase(models.Model):
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    is_activate = models.BooleanField(default=True)

    class Meta:
        abstract = True


class BookCategory(models.Model):
    name = models.CharField(max_length=128, null=False)

    class Meta:
        db_table = 'book_category'

    def __str__(self):
        return self.name


class Book(BookBase):
    LANGUAGE_CHOICES = (
        (0, 'VN'),
        (1, 'JP'),
        (2, 'EN'),
    )

    name = models.CharField(max_length=256, null=False)
    description = models.TextField()
    image = models.URLField(null=False, blank=True)
    book_category = models.ManyToManyField(BookCategory)
    author = models.CharField(max_length=128, null=True, blank=True)
    paperback = models.IntegerField(default=1)
    language = models.IntegerField(choices=LANGUAGE_CHOICES, default=0)
    publisher = models.CharField(max_length=256, null=True, blank=True)
    price = models.IntegerField(default=0)

    class Meta:
        db_table = 'book'

    def __str__(self):
        return self.name


class BookReadStatus(BookBase):
    STATUS_CHOICES = (
        (0, 'unread'),
        (1, 'reading'),
        (2, 'read'),
    )

    book = models.ForeignKey(Book, on_delete=models.CASCADE)
    user = models.ManyToManyField(User)
    status = models.IntegerField(choices=STATUS_CHOICES, default=0)
    page_reading = models.IntegerField(default=0)
    is_favorite = models.BooleanField(default=False)
    rating = models.IntegerField(default=0, validators=[MaxValueValidator(5), MinValueValidator(0)])

    class Meta:
        db_table = 'book_read_status'

    def __str(self):
        return self.page_reading


class BookRequestBuy(BookBase):
    STATUS_CHOICES = (
        (1, 'waiting'),
        (2, 'approved'),
        (3, 'bought'),
        (4, 'reject')
    )
    book_category = models.ManyToManyField(BookCategory)
    book_url = models.URLField(max_length=512)
    name = models.CharField(max_length=256)
    price = models.IntegerField(default=1)
    status = models.IntegerField(choices=STATUS_CHOICES, default=1)
    user = models.OneToOneField(User, on_delete=models.CASCADE)

    class Meta:
        db_table = 'book_request_buy'

    def __str__(self):
        return self.book_url


class BookReview(BookBase):
    book = models.OneToOneField(Book, on_delete=models.CASCADE)
    messages = ArrayField(ArrayField(models.CharField(max_length=512, blank=True), size=5))

    class Meta:
        db_table = 'book_review'

    def __str__(self):
        return self.book.name

components/books/forms.py
from django import forms
from django.core.validators import MaxValueValidator, MinValueValidator

from .models import Book, BookRequestBuy


class BookCreateForm(forms.ModelForm):
    class Meta:
        model = Book
        fields = ['name',
                  'description',
                  'image',
                  'book_category',
                  'author',
                  'paperback',
                  'language',
                  'publisher',
                  'price']


class BookUpdateForm(forms.ModelForm):
    class Meta:
        model = Book
        fields = ['name',
                  'description',
                  'image',
                  'book_category',
                  'author',
                  'paperback',
                  'language',
                  'publisher',
                  'price']


class BookMarkReadForm(forms.Form):
    page_reading = forms.IntegerField(min_value=1)


class BookFavoriteForm(forms.Form):
    is_favorite = forms.IntegerField(validators=[MinValueValidator(0), MaxValueValidator(1)])


class BookRequestBuyForm(forms.ModelForm):
    class Meta:
        model = BookRequestBuy
        fields = ['name', 'book_url', 'book_category', 'price']


class BookRequestBuyUpdateForm(forms.Form):
    status = forms.IntegerField(validators=[MinValueValidator(0), MaxValueValidator(5)])


class BookReviewCreateForm(forms.Form):
    message = forms.CharField(max_length=512)


class BookRatingCreateForm(forms.Form):
    rating = forms.IntegerField(validators=[MinValueValidator(1), MaxValueValidator(5)])


class SearchBookForm(forms.Form):
    q = forms.CharField(max_length=128)

components/books/views.py
from datetime import datetime
from django.urls import reverse
from django.db.models import Count
from django.shortcuts import render, get_object_or_404, redirect
from django.core.paginator import Paginator
from django.utils.decorators import method_decorator
from django.contrib.auth.decorators import login_required
from django.views import View
from django.contrib.postgres.search import SearchVector
from django.db.models.query import Q
from django.contrib import messages
from django.db.models import Avg

from components.users.decorators import admin_required
from .models import (
    Book, BookReadStatus, BookRequestBuy,
    BookReview, BookCategory
)
from .forms import (
    BookCreateForm, BookUpdateForm,
    BookMarkReadForm, BookFavoriteForm,
    BookRequestBuyForm, BookRequestBuyUpdateForm,
    BookReviewCreateForm, SearchBookForm, BookRatingCreateForm
)
from utility.log_activity import ActivityLog

logger = ActivityLog()


class BookListView(View):
    template_name = 'book_list.html'
    paginate_by = 25

    @method_decorator(login_required)
    def get(self, request, *args, **kwargs):
        query = Q(is_activate=True)

        books_favorite = []
        if request.GET.get('favorited') == 'true':
            books_favorite_qs = BookReadStatus.objects.filter(user=request.user,
                                                              is_favorite=True).values_list('book_id', flat=True)
            books_favorite.extend(list(books_favorite_qs))

        if request.GET.get('reading') == 'true':
            books_favorite_qs = BookReadStatus.objects.filter(user=request.user,
                                                              status=BookReadStatus.STATUS_CHOICES[1][0]
                                                              ).values_list('book_id', flat=True)
            books_favorite.extend(list(books_favorite_qs))

        if request.GET.get('read') == 'true':
            books_favorite_qs = BookReadStatus.objects.filter(user=request.user,
                                                              status=BookReadStatus.STATUS_CHOICES[2][0]
                                                              ).values_list('book_id', flat=True)
            books_favorite.extend(list(books_favorite_qs))

        if request.GET.get('favorited') == 'true' or request.GET.get('reading') == 'true' or request.GET.get(
                'read') == 'true':
            query = query & Q(id__in=list(set(books_favorite)))

        category = request.GET.get('category')
        if category:
            query = query & Q(book_category__name=category)

        books = Book.objects.filter(query).order_by('-updated_at')
        paginator = Paginator(books, self.paginate_by)

        page_number = request.GET.get('page')
        page_obj = paginator.get_page(page_number)
        return render(request, self.template_name, {'books': page_obj})


class BookDetailView(View):
    template_name = 'book_detail.html'

    @method_decorator(login_required)
    def get(self, request, *args, **kwargs):
        book_id = kwargs.get('id')
        book = get_object_or_404(Book, pk=book_id)

        book_read_status_qs = BookReadStatus.objects.filter(book=book)
        book_reviews_qs = BookReview.objects.filter(book_id=book_id).first()
        rating = book_read_status_qs.aggregate(Avg('rating'))
        rating = round(rating['rating__avg']) if rating['rating__avg'] else 0
        context = {
            'id': book_id,
            'book': book,
            'rating': rating,
            'status': book_read_status_qs.filter(user=request.user).first(),
            'reviews': book_reviews_qs.messages if book_reviews_qs else [],
            'form_comment': kwargs.get('form_comment'),
            'form_bookmark': kwargs.get('form_bookmark'),
            'form_favorite': kwargs.get('form_favorite'),
            'form_rating': kwargs.get('form_rating')
        }
        return render(request, self.template_name, context)


class BookCategoryView(View):
    template_name = 'book_category.html'

    def get(self, request, *args, **kwargs):
        book_categories = BookCategory.objects.annotate(num_book=Count('book')).order_by('name')
        return render(request, self.template_name, {'categories': list(book_categories)})


class BookSearchView(View):
    template_name = 'book_list.html'
    form_class = SearchBookForm

    @method_decorator(login_required)
    def post(self, request, *args, **kwargs):
        search_form = self.form_class(request.POST)
        if search_form.is_valid():
            search_text = search_form.cleaned_data['q']
            books_qs = Book.objects.annotate(
                search=SearchVector(
                    'name', 'description', 'book_category__name'
                )
            ).filter(search=search_text).distinct('name')
            return render(request, self.template_name, {'books': books_qs, 'q': search_text})
        return redirect(reverse('book:book-list'))


class BookCreateView(View):
    template_name = 'book_create.html'
    form_class = BookCreateForm

    @method_decorator(admin_required)
    def get(self, request, *args, **kwargs):
        categories = BookCategory.objects.all()
        context = {
            'categories': categories,
            'form': self.form_class
        }
        return render(request, self.template_name, context)

    @method_decorator(admin_required)
    def post(self, request, *args, **kwargs):
        create_book_form = self.form_class(request.POST)
        if create_book_form.is_valid():
            item = create_book_form.save()
            return redirect(reverse('book:book-detail', kwargs={'id': item.id}))
        return render(request, self.template_name, {'form': create_book_form})


class BookUpdateView(View):
    template_name = 'book_update.html'
    form_class = BookUpdateForm

    @method_decorator(admin_required)
    def get(self, request, *args, **kwargs):
        book_id = kwargs.get('id')
        categories = BookCategory.objects.all()
        book = Book.objects.filter(id=book_id).first()
        if not book:
            return render(request, '404.html', {'message': 'Book not found'})
        category_ids_selected = [item.id for item in book.book_category.all()]
        context = {
            'categories': categories,
            'category_ids_selected': category_ids_selected,
            'book': book,
            'form': self.form_class
        }
        return render(request, self.template_name, context)

    @method_decorator(admin_required)
    def post(self, request, *args, **kwargs):
        book = get_object_or_404(Book, pk=kwargs.get('id'))
        update_book_form = self.form_class(request.POST, instance=book)
        if update_book_form.is_valid():
            book = Book.objects.filter(id=kwargs.get('id')).first()
            if not book:
                return render(request, '404.html', {'message': 'Book not found'})
            update_book_form.save()
            messages.success(request, 'Update book success!')
            return redirect(reverse('book:book-detail', kwargs={'id': kwargs.get('id')}))
        return render(request, self.template_name, {'form': update_book_form})


class BookDeleteView(View):

    @method_decorator(admin_required)
    def post(self, request, *args, **kwargs):
        book_id = kwargs.get('id')
        Book.objects.filter(id=book_id).update(is_activate=False)
        return redirect(reverse('book:book-list'))


class BookMarkReadView(BookDetailView):
    form_class = BookMarkReadForm

    @method_decorator(login_required)
    def post(self, request, *args, **kwargs):
        book = get_object_or_404(Book, pk=kwargs.get('id'))

        mark_read_form = self.form_class(request.POST)
        if mark_read_form.is_valid():
            page_reading = mark_read_form.cleaned_data['page_reading']
            book_read_status_qs = BookReadStatus.objects.filter(
                user=request.user,
                book=book
            ).first()
            if book_read_status_qs and page_reading == book.paperback:
                book_read_status_qs.page_reading = page_reading
                book_read_status_qs.status = BookReadStatus.STATUS_CHOICES[2][0]
                book_read_status_qs.save()
                logger.log_activity(source_user=request.user, obj_target=book, activity=logger.READ)
            elif book_read_status_qs and page_reading < book.paperback:
                book_read_status_qs.page_reading = page_reading
                book_read_status_qs.status = BookReadStatus.STATUS_CHOICES[1][0]
                book_read_status_qs.save()
                logger.log_activity(source_user=request.user, obj_target=book,
                                    activity=f'{logger.READING}-{page_reading}')
            elif not book_read_status_qs:
                book_read_status_qs = BookReadStatus.objects.create(
                    book=book,
                    status=BookReadStatus.STATUS_CHOICES[1][0],
                    page_reading=page_reading,
                )
                book_read_status_qs.user.add(request.user)
                logger.log_activity(source_user=request.user, obj_target=book,
                                    activity=f'{logger.READING}-{page_reading} page')

            return redirect(reverse('book:book-detail', kwargs={'id': kwargs.get('id')}))
        kwargs.update({'form_bookmark': mark_read_form})
        response = self.get(request, **kwargs)
        return response


class BookFavoriteView(BookDetailView):
    form_class = BookFavoriteForm

    @method_decorator(login_required)
    def post(self, request, *args, **kwargs):
        book = get_object_or_404(Book, pk=kwargs.get('id'))
        favorite_form = self.form_class(request.POST)
        if favorite_form.is_valid():
            is_favorite = favorite_form.cleaned_data['is_favorite']
            book_read_status_qs = BookReadStatus.objects.filter(
                user=request.user,

components/books/templates/book_category.html
{% extends 'base.html' %}
{% load static %}

{% block title %} Book categories {% endblock %}
{% block page %}Book Categories {% endblock %}
{% block link %}
    <li class="breadcrumb-item">
        <a href="{% url 'book:book-list' %}">Book</a>
    </li>
    <li class="breadcrumb-item">
        <a href="{% url 'book:book-category' %}">Category</a>
    </li>
{% endblock %}
{% block content %}
    <div class="row">
        <div class="col-lg-6">
            <div class="card">
                <div class="card-header">
                    <h3 class="card-title">Striped Full Width Table</h3>
                </div>
                <!-- /.card-header -->
                <div class="card-body p-0">
                    <table class="table table-striped">
                        <thead>
                        <tr>
                            <th style="width: 10px">#</th>
                            <th>Name</th>
                            <th>Number Book</th>
                        </tr>
                        </thead>
                        <tbody>
                        {% for category in categories %}
                            <tr>
                                <td>{{ forloop.counter }}.</td>
                                <td><a href="{% url 'book:book-list' %}?category={{ category.name|urlencode }}">{{ category.name }}</a></td>
                                <td>{{ category.num_book }}</td>
                            </tr>
                        {% endfor %}
                        </tbody>
                    </table>
                </div>
                <!-- /.card-body -->
            </div>
        </div>
    </div>
{% endblock %}

components/books/templates/book_list.html
{% extends 'base.html' %}
{% load static %}

{% block title %} Book list {% endblock %}
{% block page %}Books{% endblock %}
{% block link %}
    <li class="breadcrumb-item">
        <a href="{% url 'book:book-list' %}">Book</a>
    </li>
{% endblock %}
{% block content %}
    <div class="row">
        <div class="col-lg-12">
            <div class="card">
                <div class="card-header">
                    <h3 class="card-title">Books Table</h3>
                </div>
                <!-- /.card-header -->
                <div class="card-body">
                    <table class="table table-bordered">
                        <thead>
                        <tr>
                            <th style="width: 10px">#</th>
                            <th>Name</th>
                            <th>Image</th>
                            <th>Category</th>
                            <th>Author</th>
                        </tr>
                        </thead>
                        <tbody>
                        {% for book in books %}
                            <tr>
                                <td>{{ book.id }}.</td>
                                <td><a href="{% url 'book:book-detail' id=book.id %}">{{ book.name }}</a></td>
                                <td><img src="{{ book.image }}" width="75" height="100" class="img-rounded"></td>
                                <td>
                                    {% for category in book.book_category.all %}
                                        <p>
                                            <a href="{% url 'book:book-list' %}?category={{ category.name|urlencode }}">{{ category.name }}</a>
                                        </p>
                                    {% endfor %}

                                </td>
                                <td><span>{{ book.author }}</span></td>
                            </tr>
                        {% endfor %}

                        </tbody>
                    </table>
                </div>
                <!-- /.card-body -->
                <div class="card-footer clearfix">
                    <ul class="pagination pagination-sm m-0 float-right">
                        {% if books.has_previous %}
                            <li class="page-item">
                                <a class="page-link" href="?page=1">«</a>
                            </li>
                            <li class="page-item">
                                <a class="page-link" href="?page={{ books.previous_page_number }}">prev</a>
                            </li>
                        {% endif %}
                        <li class="page-item">
                            <a class="current page-link">
                                {{ books.number }}
                            </a>
                        </li>
                        {% if books.has_next %}
                            <li class="page-item">
                                <a class="page-link" href="?page={{ books.next_page_number }}">next</a>
                            </li>
                            <li class="page-item">
                                <a class="page-link" href="?page={{ books.paginator.num_pages }}">»</a>
                            </li>
                        {% endif %}
                    </ul>
                </div>
            </div>
        </div>
    </div>
{% endblock %}
{% block custom_js %}
    <script>
        {% for book in books %}
            var book = '{{ book.to_json|escapejs }}';
            JSON.parse(book);
            console.log(book);
        {% endfor %}
    </script>
{% endblock %}

components/books/templates/book_update.html
{% extends 'base.html' %}
{% load static %}

{% block title %} Book edit {% endblock %}
{% block page %}Book Edit Information{% endblock %}
{% block link %}
    <li class="breadcrumb-item">
        <a href="{% url 'book:book-list' %}">Book</a>
    </li>
    <li class="breadcrumb-item active">
        <a href="{% url 'book:book-update' id=book.id %}">{{ book.id }}</a>
    </li>
{% endblock %}
{% block content %}
    <div class="row">
        <div class="col-lg-6">
            <div class="card card-info">
                <div class="card-header">
                    <h3 class="card-title">Edit Book Form</h3>
                </div>
                <!-- /.card-header -->
                <!-- form start -->
                <form class="form-horizontal" action="{% url 'book:book-update' id=book.id %}" method="POST">
                    {% if form.errors %}
                        {% for field in form %}
                            {% for error in field.errors %}
                                <div class="alert alert-danger">
                                    <strong>{{ field.name }} {{ error|slice:"4:" }}</strong>
                                </div>
                            {% endfor %}
                        {% endfor %}
                        {% for error in form.non_field_errors %}
                            <div class="alert alert-danger">
                                <strong>{{ error|escape }}</strong>
                            </div>
                        {% endfor %}
                    {% endif %}
                    {% csrf_token %}
                    <div class="card-body">
                        <div class="form-group row">
                            <label for="inputName" class="col-sm-2 col-form-label">Name</label>
                            <div class="col-sm-10">
                                <input type="text" class="form-control" id="inputName" placeholder="Name" name="name"
                                       value="{{ book.name }}" required>
                            </div>
                        </div>
                        <div class="form-group row">
                            <label for="inputCategory" class="col-sm-2 col-form-label">Category</label>
                            <div class="col-sm-4">
                                <select id="inputCategory" class="form-control" name="book_category" multiple>
                                    {% for category in categories %}
                                        {% if category.id in category_ids_selected %}
                                            <option value="{{ category.id }}" selected>{{ category.name }}</option>
                                        {% else %}
                                            <option value="{{ category.id }}">{{ category.name }}</option>
                                        {% endif %}
                                    {% endfor %}
                                </select>
                            </div>
                        </div>
                        <div class="form-group row">
                            <label for="inputLanguage" class="col-sm-2 col-form-label">Language</label>
                            <div class="col-sm-3">
                                <select id="inputLanguage" class="custom-select" name="language">
                                    <option value="0" {% if book.language == 0 %}selected{% endif %}>Vietnamese</option>
                                    <option value="1" {% if book.language == 1 %}selected{% endif %}>Japanese</option>
                                    <option value="2" {% if book.language == 2 %}selected{% endif %}>English</option>
                                </select>
                            </div>
                        </div>
                        <div class="form-group row">
                            <label for="inputAuthor" class="col-sm-2 col-form-label">Author</label>
                            <div class="col-sm-10">
                                <input type="text" class="form-control" id="inputAuthor" placeholder="Author"
                                       name="author" value="{{ book.author }}" required>
                            </div>
                        </div>
                        <div class="form-group row">
                            <label for="inputPublisher" class="col-sm-2 col-form-label">Publisher</label>
                            <div class="col-sm-10">
                                <input type="text" class="form-control" id="inputPublisher" placeholder="Publisher"
                                       name="publisher" value="{{ book.publisher }}" required>
                            </div>
                        </div>
                        <div class="form-group row">
                            <label for="inputImage" class="col-sm-2 col-form-label">Image</label>
                            <div class="col-sm-10">
                                <input type="url" class="form-control" id="inputImage" placeholder="Image URL"
                                       name="image" value="{{ book.image }}">
                            </div>
                        </div>
                        <div class="form-group row">
                            <label for="inputPaperback" class="col-sm-2 col-form-label">Paperback</label>
                            <div class="col-sm-2">
                                <input type="number" class="form-control" id="inputPaperback" name="paperback"
                                       value="{{ book.paperback }}">
                            </div>
                        </div>
                        <div class="form-group row">
                            <label for="inputPrice" class="col-sm-2 col-form-label">Price(VND)</label>
                            <div class="col-sm-2">
                                <input type="number" class="form-control" id="inputPrice" name="price"
                                       value="{{ book.price }}">
                            </div>
                        </div>
                        <div class="form-group row">
                            <label for="inputDescription" class="col-sm-2 col-form-label">Description</label>
                            <div class="col-sm-10">
                                <textarea class="form-control" rows="5" placeholder="Enter ..." name="description"
                                          required>{{ book.description }}</textarea>
                            </div>
                        </div>
                    </div>
                    <!-- /.card-body -->
                    <div class="card-footer">
                        <button type="submit" class="btn btn-info">Submit</button>
                        <button type="button" class="btn btn-danger float-right" data-toggle="modal"
                                data-target="#modal-delete">Remove
                        </button>
                    </div>
                    <!-- /.card-footer -->
                </form>
            </div>
        </div>
    </div>
    <div class="modal fade" id="modal-delete" aria-hidden="true" style="display: none;">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <h4 class="modal-title">Are you sure to delete this item?</h4>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">×</span>
                    </button>
                </div>
                <form action="{% url 'book:book-delete' id=book.id %}" method="post">
                    {% csrf_token %}
                    <div class="modal-footer justify-content-between">
                        <button type="submit" class="btn btn-danger">Delete</button>
                    </div>
                </form>
            </div>
            <!-- /.modal-content -->
        </div>
        <!-- /.modal-dialog -->
    </div>
{% endblock %}
{% block custom_js %}
    <script type="text/javascript">
        $(document).ready(function () {
            {% if form.errors %}
                toastr.error('Update book fail!');
            {% endif %}
        })
    </script>
{% endblock %}

components/books/templates/create_book.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>

<form action="{% url 'book:create-book' %}" method="POST">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Send message">
</form>
</body>
</html>

components/books/templates/detail_book.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<h2>Book: {{ book.name }}</h2>
{% for category in book.category.all %}
    <ul>
    <li>{{ category.name }}</li>
    </ul>
{% endfor %}
<img src="{{ book.image }}" alt="">
<div>
    {{ book.description }}
</div>
</body>
</html>

components/books/templates/list_book.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
    <h1>List Books</h1>
    {% if user.is_authenticated %}
    <p>hello</p>
    <p>welcome {{ user.username }}</p>
    <p><a href="/logout">Logout</a></p>
    {% else %}
    <p><a href="/login">Login</a></p>
    <p><a href="/register">Register</a></p>
    {% endif %}
    <ul>
    {% for book in books %}
        <li><span>{{ book.name }}</span></li>
        <li><img src="{{ book.image }}" alt=""></li>
    {% endfor %}
    </ul>

</body>
</html>

components/books/templates/update_book.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>

<form action="{% url 'book:update-book' id=id %}" method="PUT">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Send message">
</form>
</body>
</html>