brs/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', include('components.users.urls')),
    path('admin/', admin.site.urls),
    path('book/', include('components.books.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

components/books/urls.py
from django.urls import path

from .views import (
    BookListView,
    BookDetailView,
    BookSearchView,
    BookCreateView,
    BookUpdateView,
    BookMarkReadView,
    BookFavoriteView,
    BookRequestBuyCreateView,
    BookRequestBuyListView,
    BookRequestBuyUpdateView,
    BookReviewCreateView,
    BookDeleteView,
    BookCategoryView,
    BookRatingCreateView
)

app_name = 'book'

urlpatterns = [
    path('', BookListView.as_view(), name='book-list'),
    path('<int:id>/', BookDetailView.as_view(), name='book-detail'),
    path('search/', BookSearchView.as_view(), name='book-search'),
    path('category/', BookCategoryView.as_view(), name='book-category'),
    path('add/', BookCreateView.as_view(), name='book-create'),
    path('<int:id>/edit/', BookUpdateView.as_view(), name='book-update'),
    path('<int:id>/del/', BookDeleteView.as_view(), name='book-delete'),
    path('<int:id>/mark/', BookMarkReadView.as_view(), name='book-mark'),
    path('<int:id>/like/', BookFavoriteView.as_view(), name='book-like'),
    path('add-request-buy/', BookRequestBuyCreateView.as_view(), name='add-request-buy'),
    path('list-request-buy/', BookRequestBuyListView.as_view(), name='list-request-buy'),
    path('edit-request-buy/<int:id>', BookRequestBuyUpdateView.as_view(), name='edit-request-buy'),
    path('<int:id>/review/', BookReviewCreateView.as_view(), name='book-review'),
    path('<int:id>/rating/', BookRatingCreateView.as_view(), name='book-rating'),
]

components/users/urls.py
from django.urls import path

from .views import (
    UserDetailView,
    AdminDashboardView,
    UserUpdateView,
    SignUpView,
    SignInView,
    SignOutView,
    UserListView,
    ChangeRoleUserView,
    UserFollowUpdateCreateView,
    UserFollowedListView
)

app_name = 'users'

urlpatterns = [
    path('signup', SignUpView.as_view(), name='signup'),
    path('signin', SignInView.as_view(), name='signin'),
    path('signout', SignOutView.as_view(), name='signout'),

    path('user/<int:id>/change-role/', ChangeRoleUserView.as_view(), name='change-role'),
    path('users/', UserListView.as_view(), name='users-list'),
    path('user/<int:id>/edit/', UserUpdateView.as_view(), name='user-update'),
    path('user/<int:id>/', UserDetailView.as_view(), name='user-detail'),
    path('dashboard/', AdminDashboardView.as_view(), name='dashboard'),
    path('user/follow/', UserFollowUpdateCreateView.as_view(), name='user-follow'),
    path('user/followed/', UserFollowedListView.as_view(), name='user-followed')
]

templates/includes/footer.html
<footer class="main-footer">
    <strong>Copyright © 2020 <a href="http://adminlte.io">AdminLTE.io</a>.</strong>
    All rights reserved.
    <div class="float-right d-none d-sm-inline-block">
        <b>Version</b> 3.0.4
    </div>
</footer>

templates/includes/header.html
{% load static %}

<!-- Navbar -->
<nav class="main-header navbar navbar-expand navbar-white navbar-light">
    <!-- Left navbar links -->
    <ul class="navbar-nav">
        <li class="nav-item">
            <a class="nav-link" data-widget="pushmenu" href="#" role="button"><i class="fas fa-bars"></i></a>
        </li>
        <li class="nav-item d-none d-sm-inline-block">
            <a href="{% url 'book:book-list' %}" class="nav-link">Books</a>
        </li>
        {% if user.role == 1 %}
            <li class="nav-item d-none d-sm-inline-block">
                <a href="{% url 'users:users-list' %}" class="nav-link">Users</a>
            </li>
        {% endif %}
    </ul>

    <!-- SEARCH FORM -->
    <form class="form-inline ml-3" action="{% url 'book:book-search' %}" method="POST">
        {% csrf_token %}
        <div class="input-group input-group-sm">
            <input class="form-control form-control-navbar" type="search" placeholder="Search" aria-label="Search"
                   name="q" {% if q %}value="{{ q }}"{% endif %}>
            <div class="input-group-append">
                <button class="btn btn-navbar" type="submit">
                    <i class="fas fa-search"></i>
                </button>
            </div>
        </div>
    </form>

    <!-- Right navbar links -->
    <ul class="navbar-nav ml-auto">
        <!-- Messages Dropdown Menu -->
        <li class="nav-item dropdown">
            <a class="nav-link" data-toggle="dropdown" href="#">
                <i class="far fa-comments"></i>
                <span class="badge badge-danger navbar-badge">3</span>
            </a>
            <div class="dropdown-menu dropdown-menu-lg dropdown-menu-right">
                <a href="#" class="dropdown-item">
                    <!-- Message Start -->
                    <div class="media">
                        <img src="{% static 'img/user1-128x128.jpg' %}" alt="User Avatar"
                             class="img-size-50 mr-3 img-circle">
                        <div class="media-body">
                            <h3 class="dropdown-item-title">
                                Brad Diesel
                                <span class="float-right text-sm text-danger"><i class="fas fa-star"></i></span>
                            </h3>
                            <p class="text-sm">Call me whenever you can...</p>
                            <p class="text-sm text-muted"><i class="far fa-clock mr-1"></i> 4 Hours Ago</p>
                        </div>
                    </div>
                    <!-- Message End -->
                </a>
                <div class="dropdown-divider"></div>
                <a href="#" class="dropdown-item">
                    <!-- Message Start -->
                    <div class="media">
                        <img src="{% static 'img/user8-128x128.jpg' %}" alt="User Avatar"
                             class="img-size-50 img-circle mr-3">
                        <div class="media-body">
                            <h3 class="dropdown-item-title">
                                John Pierce
                                <span class="float-right text-sm text-muted"><i class="fas fa-star"></i></span>
                            </h3>
                            <p class="text-sm">I got your message bro</p>
                            <p class="text-sm text-muted"><i class="far fa-clock mr-1"></i> 4 Hours Ago</p>
                        </div>
                    </div>
                    <!-- Message End -->
                </a>
                <div class="dropdown-divider"></div>
                <a href="#" class="dropdown-item">
                    <!-- Message Start -->
                    <div class="media">
                        <img src="{% static 'img/user3-128x128.jpg' %}" alt="User Avatar"
                             class="img-size-50 img-circle mr-3">
                        <div class="media-body">
                            <h3 class="dropdown-item-title">
                                Nora Silvester
                                <span class="float-right text-sm text-warning"><i class="fas fa-star"></i></span>
                            </h3>
                            <p class="text-sm">The subject goes here</p>
                            <p class="text-sm text-muted"><i class="far fa-clock mr-1"></i> 4 Hours Ago</p>
                        </div>
                    </div>
                    <!-- Message End -->
                </a>
                <div class="dropdown-divider"></div>
                <a href="#" class="dropdown-item dropdown-footer">See All Messages</a>
            </div>
        </li>
        <!-- Notifications Dropdown Menu -->
        <li class="nav-item dropdown">
            <a class="nav-link" data-toggle="dropdown" href="#">
                <i class="far fa-bell"></i>
                <span class="badge badge-warning navbar-badge">15</span>
            </a>
            <div class="dropdown-menu dropdown-menu-lg dropdown-menu-right">
                <span class="dropdown-item dropdown-header">15 Notifications</span>
                <div class="dropdown-divider"></div>
                <a href="#" class="dropdown-item">
                    <i class="fas fa-envelope mr-2"></i> 4 new messages
                    <span class="float-right text-muted text-sm">3 mins</span>
                </a>
                <div class="dropdown-divider"></div>
                <a href="#" class="dropdown-item">
                    <i class="fas fa-users mr-2"></i> 8 friend requests
                    <span class="float-right text-muted text-sm">12 hours</span>
                </a>
                <div class="dropdown-divider"></div>
                <a href="#" class="dropdown-item">
                    <i class="fas fa-file mr-2"></i> 3 new reports
                    <span class="float-right text-muted text-sm">2 days</span>
                </a>
                <div class="dropdown-divider"></div>
                <a href="#" class="dropdown-item dropdown-footer">See All Notifications</a>
            </div>
        </li>
    </ul>
</nav>

templates/includes/show_messages.html
{% if messages %}
    {% for message in messages %}
    <div class="alert {{ message.tags|default:'alert-success' }} alert-dismissable">
        <button type="button" class="close" data-dismiss="alert" aria-hidden="true">×</button>
        {{ message }}
    </div>
    {% endfor %}
{% endif %}

templates/includes/siderbar.html
{% load static %}
<div class="sidebar">
    <!-- Sidebar user panel (optional) -->
    <div class="user-panel mt-3 pb-3 mb-3 d-flex">
        <div class="image">
            <img src="{% if user.avatar %}/media/{{ user.avatar }}{% else %}{% static 'img/user2-160x160.jpg' %}{% endif %}" class="img-circle elevation-2" alt="User Image">
        </div>
        <div class="info">
            <a href="{% url 'users:user-detail' id=user.id %}" class="d-block">{{ user.username }}</a>
            <small><a href="{% url 'users:signout' %}">SignOut</a></small>
        </div>
    </div>

    <!-- Sidebar Menu -->
    <nav class="mt-2">
        <ul class="nav nav-pills nav-sidebar flex-column" data-widget="treeview" role="menu"
            data-accordion="false">
            <!-- Add icons to the links using the .nav-icon class
                 with font-awesome or any other icon font library -->
            <li class="nav-item has-treeview menu-open">
                <a href="{% url 'book:book-list' %}" class="nav-link {% if '/book' in request.path %}active{% endif %}">
                    <i class="nav-icon fa fa-book"></i>
                    <p>
                        Book
                        <i class="right fas fa-angle-left"></i>
                    </p>
                </a>
                <ul class="nav nav-treeview">
                    <li class="nav-item">
                        <a href="{% url 'book:book-list' %}"
                           class="nav-link {% if not request.GET and not '/book/category/' == request.path %}active{% endif %}">
                            <i class="far fa-circle nav-icon"></i>
                            <p>All</p>
                        </a>
                    </li>
                    <li class="nav-item">
                        <a href="{% url 'book:book-category' %}" class="nav-link {% if '/book/category/' == request.path %}active{% endif %}">
                            <i class="fa fa-list-alt nav-icon"></i>
                            <p>Category</p>
                        </a>
                    </li>
                    <li class="nav-item">
                        <a href="{% url 'book:book-list' %}?favorited=true" class="nav-link {% if request.GET.favorited == 'true' %}active{% endif %}">
                            <i class="far fa-thumbs-up nav-icon"></i>
                            <p>Favorite</p>
                        </a>
                    </li>
                    <li class="nav-item">
                        <a href="{% url 'book:book-list' %}?reading=true" class="nav-link {% if request.GET.reading == 'true' %}active{% endif %}">
                            <i class="far fa-circle nav-icon"></i>
                            <p>Reading</p>
                        </a>
                    </li>
                    <li class="nav-item">
                        <a href="{% url 'book:book-list' %}?read=true" class="nav-link {% if request.GET.read == 'true' %}active{% endif %}">
                            <i class="far fa-circle nav-icon"></i>
                            <p>Read</p>
                        </a>
                    </li>
                    <li class="nav-item">
                        <a href="{% url 'book:list-request-buy' %}" class="nav-link">
                            <i class="fa fa-shopping-cart nav-icon"></i>
                            <p>Request Buy</p>
                        </a>
                    </li>
                    {% if user.role == 1 %}
                        <li class="nav-item">
                            <a href="{% url 'book:book-create' %}" class="nav-link">
                                <i class="far fa-circle nav-icon"></i>
                                <p>Add Book</p>
                            </a>
                        </li>
                    {% endif %}
                </ul>
            </li>
            <li class="nav-item has-treeview menu-open">
                <a href="{% url 'users:users-list' %}"
                   class="nav-link {% if '/user' in request.path %}active{% endif %}">
                    <i class="nav-icon fa fa-user"></i>
                    <p>
                        Users
                        <i class="right fas fa-angle-left"></i>
                    </p>
                </a>
                <ul class="nav nav-treeview">
                    <li class="nav-item">
                        <a href="{% url 'users:users-list' %}"
                           class="nav-link {% if request.path == '/users/' %}active{% endif %}">
                            <i class="far fa-circle nav-icon"></i>
                            <p>All</p>
                        </a>
                    </li>
                    <li class="nav-item">
                        <a href="{% url 'users:user-followed' %}" class="nav-link">
                            <i class="far fa-circle nav-icon"></i>
                            <p>User Followed</p>
                        </a>
                    </li>
                </ul>
            </li>
        </ul>
    </nav>
    <!-- /.sidebar-menu -->
</div>