brs/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', include('components.users.urls')),
    path('admin/', admin.site.urls),
    path('book/', include('components.books.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

components/books/urls.py
from django.urls import path

from .views import (
    BookListView,
    BookDetailView,
    BookSearchView,
    BookCreateView,
    BookUpdateView,
    BookMarkReadView,
    BookFavoriteView,
    BookRequestBuyCreateView,
    BookRequestBuyListView,
    BookRequestBuyUpdateView,
    BookReviewCreateView,
    BookDeleteView,
    BookCategoryView,
    BookRatingCreateView
)

app_name = 'book'

urlpatterns = [
    path('', BookListView.as_view(), name='book-list'),
    path('<int:id>/', BookDetailView.as_view(), name='book-detail'),
    path('search/', BookSearchView.as_view(), name='book-search'),
    path('category/', BookCategoryView.as_view(), name='book-category'),
    path('add/', BookCreateView.as_view(), name='book-create'),
    path('<int:id>/edit/', BookUpdateView.as_view(), name='book-update'),
    path('<int:id>/del/', BookDeleteView.as_view(), name='book-delete'),
    path('<int:id>/mark/', BookMarkReadView.as_view(), name='book-mark'),
    path('<int:id>/like/', BookFavoriteView.as_view(), name='book-like'),
    path('add-request-buy/', BookRequestBuyCreateView.as_view(), name='add-request-buy'),
    path('list-request-buy/', BookRequestBuyListView.as_view(), name='list-request-buy'),
    path('edit-request-buy/<int:id>', BookRequestBuyUpdateView.as_view(), name='edit-request-buy'),
    path('<int:id>/review/', BookReviewCreateView.as_view(), name='book-review'),
    path('<int:id>/rating/', BookRatingCreateView.as_view(), name='book-rating'),
]

components/users/urls.py
from django.urls import path

from .views import (
    UserDetailView,
    AdminDashboardView,
    UserUpdateView,
    SignUpView,
    SignInView,
    SignOutView,
    UserListView,
    ChangeRoleUserView,
    UserFollowUpdateCreateView,
    UserFollowedListView
)

app_name = 'users'

urlpatterns = [
    path('signup', SignUpView.as_view(), name='signup'),
    path('signin', SignInView.as_view(), name='signin'),
    path('signout', SignOutView.as_view(), name='signout'),

    path('user/<int:id>/change-role/', ChangeRoleUserView.as_view(), name='change-role'),
    path('users/', UserListView.as_view(), name='users-list'),
    path('user/<int:id>/edit/', UserUpdateView.as_view(), name='user-update'),
    path('user/<int:id>/', UserDetailView.as_view(), name='user-detail'),
    path('dashboard/', AdminDashboardView.as_view(), name='dashboard'),
    path('user/follow/', UserFollowUpdateCreateView.as_view(), name='user-follow'),
    path('user/followed/', UserFollowedListView.as_view(), name='user-followed')
]

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>{% block title %}{% endblock %}</title>
    <!-- Tell the browser to be responsive to screen width -->
    <meta content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no" name="viewport">
    <!-- Font Awesome -->
    <link rel="stylesheet" href="{% static 'plugins/fontawesome-free/css/all.min.css' %}">
    <!-- Ionicons -->
    <link rel="stylesheet" href="https://code.ionicframework.com/ionicons/2.0.1/css/ionicons.min.css">
    <!-- Theme style -->
    <link rel="stylesheet" href="{% static 'css/adminlte.min.css' %}">

    <!-- Toastr theme -->
    <link rel="stylesheet" href="{% static 'plugins/toastr/toastr.min.css' %}">
    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
                <script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
                <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
            <![endif]-->

    <!-- Google Font -->
    <link rel="stylesheet"
          href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,400i,700">
    {% block custom_css %}{% endblock %}
</head>
<body class="hold-transition sidebar-mini layout-fixed">
<div class="wrapper">

    <!-- Navbar -->
    {% include './includes/header.html' %}
    <!-- /.navbar -->

    <!-- Main Sidebar Container -->
    <aside class="main-sidebar sidebar-dark-primary elevation-4">
        <!-- Brand Logo -->
        <a href="{% if user.role == 1 %}{% url 'users:dashboard' %}{% else %}{% url 'book:book-list' %}{% endif %}"
           class="brand-link">
            <img src="{% static 'img/logo_sun.png' %}" alt="AdminLTE Logo"
                 class="brand-image img-circle elevation-3"
                 style="opacity: .8">
            <span class="brand-text font-weight-light">Sun Library</span>
        </a>

        <!-- Sidebar -->
        {% include './includes/siderbar.html' %}
        <!-- /.sidebar -->
    </aside>

    <!-- Content Wrapper. Contains page content -->
    <div class="content-wrapper">
        <!-- Content Header (Page header) -->
        <div class="content-header">
            <div class="container-fluid">
                <div class="row mb-2">
                    <div class="col-sm-6">
                        <h1 class="m-0 text-dark">{% block page %}{% endblock %}</h1>
                    </div><!-- /.col -->
                    <div class="col-sm-6">
                        <ol class="breadcrumb float-sm-right">
                            <li class="breadcrumb-item"><a href="
                                    {% if user.role == 1 %}{% url 'users:dashboard' %}{% else %}{% url 'book:book-list' %}{% endif %}">Home</a>
                            </li>
                            {% block link %}{% endblock %}
                        </ol>
                    </div><!-- /.col -->
                </div><!-- /.row -->
            </div><!-- /.container-fluid -->
        </div>
        <!-- /.content-header -->

        <!-- Main content -->
        <section class="content">
            <div class="container-fluid">
                <!-- Small boxes (Stat box) -->
                {% block content %}{% endblock %}
                <!-- /.row (main row) -->
            </div><!-- /.container-fluid -->
        </section>
        <!-- /.content -->
    </div>
    <!-- /.content-wrapper -->

    {% include './includes/footer.html' %}

    <!-- Control Sidebar -->
    <aside class="control-sidebar control-sidebar-dark">
        <!-- Control sidebar content goes here -->
    </aside>
    <!-- /.control-sidebar -->

    <!-- jQuery -->
    <script src="{% static 'plugins/jquery/jquery.min.js' %}"></script>
    <!-- jQuery UI 1.11.4 -->
    <script src="{% static 'plugins/jquery-ui/jquery-ui.min.js' %}"></script>
    <!-- Bootstrap 4 -->
    <script src="{% static 'plugins/bootstrap/js/bootstrap.bundle.min.js' %}"></script>
    <!-- AdminLTE App -->
    <script src="{% static 'js/adminlte.min.js' %}"></script>

    <!-- Toastr -->
    <script src="{% static 'plugins/toastr/toastr.min.js' %}"></script>

    {% block custom_js %}{% endblock %}
</div>
</body>
</html>