brs/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', include('components.users.urls')),
    path('admin/', admin.site.urls),
    path('book/', include('components.books.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

components/books/urls.py
from django.urls import path

from .views import (
    BookListView,
    BookDetailView,
    BookSearchView,
    BookCreateView,
    BookUpdateView,
    BookMarkReadView,
    BookFavoriteView,
    BookRequestBuyCreateView,
    BookRequestBuyListView,
    BookRequestBuyUpdateView,
    BookReviewCreateView,
    BookDeleteView,
    BookCategoryView,
    BookRatingCreateView
)

app_name = 'book'

urlpatterns = [
    path('', BookListView.as_view(), name='book-list'),
    path('<int:id>/', BookDetailView.as_view(), name='book-detail'),
    path('search/', BookSearchView.as_view(), name='book-search'),
    path('category/', BookCategoryView.as_view(), name='book-category'),
    path('add/', BookCreateView.as_view(), name='book-create'),
    path('<int:id>/edit/', BookUpdateView.as_view(), name='book-update'),
    path('<int:id>/del/', BookDeleteView.as_view(), name='book-delete'),
    path('<int:id>/mark/', BookMarkReadView.as_view(), name='book-mark'),
    path('<int:id>/like/', BookFavoriteView.as_view(), name='book-like'),
    path('add-request-buy/', BookRequestBuyCreateView.as_view(), name='add-request-buy'),
    path('list-request-buy/', BookRequestBuyListView.as_view(), name='list-request-buy'),
    path('edit-request-buy/<int:id>', BookRequestBuyUpdateView.as_view(), name='edit-request-buy'),
    path('<int:id>/review/', BookReviewCreateView.as_view(), name='book-review'),
    path('<int:id>/rating/', BookRatingCreateView.as_view(), name='book-rating'),
]

components/users/urls.py
from django.urls import path

from .views import (
    UserDetailView,
    AdminDashboardView,
    UserUpdateView,
    SignUpView,
    SignInView,
    SignOutView,
    UserListView,
    ChangeRoleUserView,
    UserFollowUpdateCreateView,
    UserFollowedListView
)

app_name = 'users'

urlpatterns = [
    path('signup', SignUpView.as_view(), name='signup'),
    path('signin', SignInView.as_view(), name='signin'),
    path('signout', SignOutView.as_view(), name='signout'),

    path('user/<int:id>/change-role/', ChangeRoleUserView.as_view(), name='change-role'),
    path('users/', UserListView.as_view(), name='users-list'),
    path('user/<int:id>/edit/', UserUpdateView.as_view(), name='user-update'),
    path('user/<int:id>/', UserDetailView.as_view(), name='user-detail'),
    path('dashboard/', AdminDashboardView.as_view(), name='dashboard'),
    path('user/follow/', UserFollowUpdateCreateView.as_view(), name='user-follow'),
    path('user/followed/', UserFollowedListView.as_view(), name='user-followed')
]

components/users/models.py
from django.contrib.auth.base_user import AbstractBaseUser
from django.contrib.auth.models import UserManager
from django.utils.translation import gettext_lazy as _
from django.db import models


def user_directory_path(instance, filename):
    # Uploaded to MEDIA_ROOT / user_<id>/<filename>
    return f'user_{instance.id}/avatar/{filename}'


class UserBase(models.Model):
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    is_activate = models.BooleanField(default=True)

    class Meta:
        abstract = True


class User(AbstractBaseUser, UserBase):
    ROLE_ADMIN = 1
    ROLE_MEMBER = 2
    USER_ROLES = (
        (ROLE_ADMIN, 'Sun Admin'),
        (ROLE_MEMBER, 'Sun Memeber'),
    )

    username = models.CharField(_('username'), max_length=150)
    email = models.EmailField(_('email address'), blank=True, null=True, unique=True)
    role = models.IntegerField(choices=USER_ROLES, default=ROLE_MEMBER)
    is_activate = models.BooleanField(default=False)
    avatar = models.ImageField(upload_to=user_directory_path, null=True)
    education = models.CharField(max_length=256, null=True)
    location = models.CharField(max_length=256, null=True)
    skills = models.CharField(max_length=256, null=True)
    notes = models.TextField(null=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = ['username']

    objects = UserManager()

    class Meta:
        db_table = 'user'

    def __str__(self):
        return 'User: {}'.format(self.username)


class UserFollow(UserBase):
    STATUS_FOLLOW = (
        (1, 'unfollow'),
        (2, 'follow')
    )
    follower = models.ForeignKey(User, related_name='following', on_delete=models.CASCADE, null=True)
    following = models.ForeignKey(User, related_name='followers', on_delete=models.CASCADE, null=True)
    status = models.IntegerField(choices=STATUS_FOLLOW, default=1)

    class Meta:
        db_table = 'user_follow'
        unique_together = ('follower', 'following')

    def __str__(self):
        return f'{self.follower.username} follows {self.following.username}'

components/users/forms.py
import datetime
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.core.exceptions import ValidationError
from django.core.validators import MinValueValidator, MaxValueValidator
from django.contrib.auth import authenticate

from .models import User
from utility.utility import verify_email_format


class SignUpForm(UserCreationForm):
    terms = forms.CharField()

    class Meta:
        model = User
        fields = ['email', 'password1', 'password2', 'terms']

    def clean_email(self):
        email = self.cleaned_data['email']
        if User.objects.filter(email=email).exists():
            raise forms.ValidationError('Email is exist!')
        if not verify_email_format(self.cleaned_data.get('email')):
            raise ValidationError("Email is not Sun Asterisk email")

        return email

    def clean_terms(self):
        if self.cleaned_data['terms'] != 'on':
            raise ValidationError("You forgot check on terms")

        return True

    def clean(self):
        password1 = self.cleaned_data.get('password1')
        password2 = self.cleaned_data.get('password2')
        if password1 != password2:
            raise ValidationError("Password and confirm password not match")

    def save(self, commit=True):
        data = self.cleaned_data
        user = User.objects.create(
            email=data.get('email'),
            username=data.get('email'),
            is_activate=True
        )
        user.set_password(data.get('password1'))
        user.last_login = datetime.datetime.now()
        user.save()

        return user


class SignInForm(forms.Form):
    email = forms.CharField(min_length=1, max_length=150)
    password = forms.CharField(min_length=1, max_length=128)

    def clean(self):
        cleaned_data = super().clean()
        user = authenticate(username=cleaned_data.get('email'),
                            password=cleaned_data.get('password'))
        msg = 'Email and password not matching!'
        if not user:
            raise ValidationError(msg)


class ChangeRoleAccountForm(forms.Form):
    username = forms.CharField(max_length=150)
    role = forms.IntegerField(validators=[MinValueValidator(1), MaxValueValidator(2)])


class UserUpdateForm(forms.ModelForm):
    class Meta:
        model = User
        fields = ['username', 'education', 'location', 'skills', 'notes']


class UserFollowForm(forms.Form):
    following_id = forms.IntegerField()
    status = forms.IntegerField(validators=[MinValueValidator(1), MaxValueValidator(2)])

components/users/views.py
from django.core.files.storage import FileSystemStorage
from django.core.paginator import Paginator
from django.db.models import Count
from django.http import HttpResponseForbidden
from django.urls import reverse
from django.shortcuts import render, redirect
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth import login, logout, authenticate
from django.contrib.auth.decorators import login_required
from django.utils.decorators import method_decorator
from django.contrib import messages
from django.views import View

from .forms import (
    SignInForm, SignUpForm,
    ChangeRoleAccountForm,
    UserUpdateForm, UserFollowForm
)

from components.books.models import Book, BookRequestBuy, BookReadStatus

from .models import User, UserFollow
from .decorators import admin_required
from utility.log_activity import ActivityLog

logger = ActivityLog()


class SignUpView(View):
    template_name = 'signup.html'

    def get(self, request, *args, **kwargs):
        return render(request, self.template_name, {'form': UserCreationForm})

    def post(self, request, *args, **kwargs):
        signup_form = SignUpForm(request.POST)
        if signup_form.is_valid():
            user = signup_form.save()
            login(request, user)

            return redirect(reverse('book:book-list'))
        return render(request, self.template_name, {'form': signup_form})


class SignInView(View):
    template_name = 'signin.html'
    form_class = SignInForm

    def get(self, request, *args, **kwargs):
        return render(request, self.template_name, {'form': self.form_class})

    def post(self, request, *args, **kwargs):
        signin_form = self.form_class(request.POST)
        if signin_form.is_valid():
            user = authenticate(username=signin_form.cleaned_data['email'],
                                password=signin_form.cleaned_data['password'])
            login(request, user)
            if user and user.role == 2:
                return redirect(reverse('book:book-list'))
            elif user and user.role == 1:
                return redirect(reverse('users:dashboard'))
        return render(request, self.template_name, {'form': signin_form})


class SignOutView(View):

    def get(self, request, *args, **kwargs):
        logout(request)
        return redirect(reverse('users:signin'))


class UserListView(View):
    template_name = 'users_list.html'

    @method_decorator(login_required)
    def get(self, request, *args, **kwargs):
        users = User.objects.filter(is_activate=True)
        return render(request, self.template_name, {'users': users})


class UserDetailView(View):
    template_name = 'user_detail.html'
    LIMIT_ACTIVITY = 10

    @method_decorator(login_required)
    def get(self, request, *args, **kwargs):
        user = User.objects.filter(id=kwargs.get('id')).first()
        activity_log = logger.get_activity_log(user=user, limit=10)
        if not user:
            return render(request, '404.html', {'message': 'User not found'})

        follow_qs = UserFollow.objects.filter(follower=request.user, following=user).first()
        follow_status = 1 if not follow_qs else follow_qs.status
        following_count = UserFollow.objects.filter(follower=user, status=UserFollow.STATUS_FOLLOW[1][0]).count()
        follower_count = UserFollow.objects.filter(following=user, status=UserFollow.STATUS_FOLLOW[1][0]).count()
        context = {
            'member': user,
            'activities': activity_log,
            'follow_status': follow_status,
            'following_count': following_count,
            'follower_count': follower_count,
            'form_role': kwargs.get('form_role'),
            'form_profile': kwargs.get('form_profile'),
            'form_follow': kwargs.get('form_follow')
        }
        return render(request, self.template_name, context=context)


class UserUpdateView(UserDetailView):
    form_class = UserUpdateForm

    @method_decorator(login_required)
    def post(self, request, *args, **kwargs):
        user_update_form = UserUpdateForm(request.POST)
        if user_update_form.is_valid():
            if request.user.id != kwargs.get('id') and request.user.role != 1:
                return HttpResponseForbidden('403 Forbidden')

            user = User.objects.filter(id=kwargs.get('id')).first()
            if not user:
                return render(request, '404.html', {'message': 'User not found'})
            user.username = user_update_form.cleaned_data['username']
            user.email = user_update_form.cleaned_data['username']
            user.education = user_update_form.cleaned_data['education']
            user.skills = user_update_form.cleaned_data['skills']
            user.notes = user_update_form.cleaned_data['notes']
            user.location = user_update_form.cleaned_data['location']
            if request.FILES.get('avatar'):
                user.avatar = request.FILES['avatar']
            user.save()

            return redirect(reverse('users:user-detail', kwargs={'id': user.id}))
        kwargs.update({'form_profile': user_update_form})
        response = self.get(request, *kwargs)
        return response


class ChangeRoleUserView(UserDetailView):
    form_class = ChangeRoleAccountForm

    @method_decorator(admin_required)
    def post(self, request, *args, **kwargs):
        change_role_account_form = ChangeRoleAccountForm(request.POST)
        if change_role_account_form.is_valid():
            username = change_role_account_form.cleaned_data['username']
            user = User.objects.filter(username=username).first()
            if user:
                user.role = int(change_role_account_form.cleaned_data['role'])
                user.save()
                return redirect(reverse('users:user-detail', kwargs={'id': user.id}))
            return render(request, '404.html', {'message': f'User {user.username} not found'})

        kwargs.update({'form_role': change_role_account_form})
        response = self.get(request, **kwargs)
        return response


class UserFollowUpdateCreateView(UserDetailView):
    form_class = UserFollowForm

    @method_decorator(login_required)
    def post(self, request, *args, **kwargs):
        follow_form = self.form_class(request.POST)
        if follow_form.is_valid():
            follower = request.user
            following = follow_form.cleaned_data['following_id']
            status = follow_form.cleaned_data['status']
            follow_qs = UserFollow.objects.filter(follower=follower, following__id=following).first()
            if not follow_qs:
                following_user = User.objects.get(id=following)
                UserFollow.objects.create(follower=follower, following=following_user, status=status)
            else:
                follow_qs.status = status
                follow_qs.save()

            return redirect(reverse('users:user-detail', kwargs={'id': following}))
        kwargs.update({'form_follow': follow_form})
        response = self.get(request, **kwargs)
        return response


class AdminDashboardView(View):
    template_name = 'dashboard.html'

    @method_decorator(admin_required)
    def get(self, request, *args, **kwargs):
        users_count = User.objects.all().count()
        books_count = Book.objects.all().count()
        books_request_buy_count = BookRequestBuy.objects.filter(status=BookRequestBuy.STATUS_CHOICES[0][0]).count()
        most_read_books = BookReadStatus.objects.filter(status__in=[1, 2]).values('book__id',
                                                                                  'book__name',
                                                                                  'book__author').annotate(
            total=Count('book')).order_by('-total')[:5]
        most_followed_users = UserFollow.objects.filter(status=2).values('following__id',
                                                                         'following__username',
                                                                         'following__role').annotate(
            total=Count('following')).order_by('-total')[:5]
        most_read_book_members = BookReadStatus.objects.filter(status__in=[1, 2]).values('user__id',
                                                                                         'user__username',
                                                                                         'user__role').annotate(
            total=Count('user')).order_by('-total')[:5]
        users_login = User.objects.filter(is_activate=True).order_by('-last_login')
        context = {
            'users_count': users_count,
            'books_count': books_count,
            'books_request_buy_count': books_request_buy_count,
            'most_read_books': most_read_books,
            'most_followed_users': most_followed_users,
            'most_read_book_members': most_read_book_members,
            'users_login': users_login

        }
        return render(request, self.template_name, context=context)


class UserFollowedListView(View):
    template_name = 'user_followed_list.html'
    paginate_by = 25

    @method_decorator(login_required)
    def get(self, request, *args, **kwargs):
        users_followed = UserFollow.objects.filter(follower=request.user, status=UserFollow.STATUS_FOLLOW[1][0])

        paginator = Paginator(users_followed, self.paginate_by)
        page_number = request.GET.get('page')
        page_obj = paginator.get_page(page_number)
        return render(request, self.template_name, {'users_followed': page_obj})

components/users/templates/dashboard.html
{% extends 'base.html' %}
{% load static %}

{% block title %} Dashboard {% endblock %}
{% block page %}Dashboard{% endblock %}
{% block link %}
    <li class="breadcrumb-item active">
        <a href="{% url 'users:dashboard' %}">Dashboard</a>
    </li>
{% endblock %}
{% block content %}
    <div class="row">
        <div class="col-lg-3 col-6">
            <!-- small box -->
            <div class="small-box bg-info">
                <div class="inner">
                    <h3>{{ books_request_buy_count }}</h3>

                    <p>New Request Buy Book</p>
                </div>
                <div class="icon">
                    <i class="ion ion-bag"></i>
                </div>
                <a href="#" class="small-box-footer">More info <i class="fas fa-arrow-circle-right"></i></a>
            </div>
        </div>
        <!-- ./col -->
        <div class="col-lg-3 col-6">
            <!-- small box -->
            <div class="small-box bg-success">
                <div class="inner">
                    <h3>{{ books_count }}</h3>

                    <p>Books</p>
                </div>
                <div class="icon">
                    <i class="ion ion-stats-bars"></i>
                </div>
                <a href="{% url 'book:book-list' %}" class="small-box-footer">More info <i
                        class="fas fa-arrow-circle-right"></i></a>
            </div>
        </div>
        <!-- ./col -->
        <div class="col-lg-3 col-6">
            <!-- small box -->
            <div class="small-box bg-warning">
                <div class="inner">
                    <h3>{{ users_count }}</h3>

                    <p>User Registrations</p>
                </div>
                <div class="icon">
                    <i class="ion ion-person-add"></i>
                </div>
                <a href="{% url 'users:users-list' %}" class="small-box-footer">More info <i
                        class="fas fa-arrow-circle-right"></i></a>
            </div>
        </div>
        <!-- ./col -->
        <div class="col-lg-3 col-6">
            <!-- small box -->
            <div class="small-box bg-danger">
                <div class="inner">
                    <h3>65</h3>

                    <p>Unique Visitors</p>
                </div>
                <div class="icon">
                    <i class="ion ion-pie-graph"></i>
                </div>
                <a href="#" class="small-box-footer">More info <i class="fas fa-arrow-circle-right"></i></a>
            </div>
        </div>
        <!-- ./col -->
    </div>
    <div class="row">
        <div class="col-lg-6">
            <div class="card">
                <div class="card-header border-0">
                    <h3 class="card-title"><b>Top 5 most read books</b></h3>
                    <div class="card-tools">
                        <a href="#" class="btn btn-tool btn-sm">
                            <i class="fas fa-download"></i>
                        </a>
                        <a href="#" class="btn btn-tool btn-sm">
                            <i class="fas fa-bars"></i>
                        </a>
                    </div>
                </div>
                <div class="card-body table-responsive p-0">
                    <table class="table table-striped table-valign-middle">
                        <thead>
                        <tr>
                            <th>#</th>
                            <th>Book</th>
                            <th>Author</th>
                            <th>Total(book)</th>
                        </tr>
                        </thead>
                        <tbody>

                        {% for item in most_read_books %}
                            <tr>
                                <td>{{ forloop.counter }}</td>
                                <td><a href="{% url 'book:book-detail' id=item.book__id %}">{{ item.book__name }}</a>
                                </td>
                                <td><p>{{ item.book__author }}</p>
                                </td>
                                <td>{{ item.total }}</td>
                            </tr>
                        {% endfor %}
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
        <div class="col-lg-6">
            <div class="card">
                <div class="card-header border-0">
                    <h3 class="card-title"><b>Top 5 most followed members</b></h3>
                    <div class="card-tools">
                        <a href="#" class="btn btn-tool btn-sm">
                            <i class="fas fa-download"></i>
                        </a>
                        <a href="#" class="btn btn-tool btn-sm">
                            <i class="fas fa-bars"></i>
                        </a>
                    </div>
                </div>
                <div class="card-body table-responsive p-0">
                    <table class="table table-striped table-valign-middle">
                        <thead>
                        <tr>
                            <th>#</th>
                            <th>Username</th>
                            <th>Role</th>
                            <th>Total(user)</th>
                        </tr>
                        </thead>
                        <tbody>
                        {% for item in most_followed_users %}
                            <tr>
                                <td>{{ forloop.counter }}</td>
                                <td>
                                    <a href="{% url 'users:user-detail' id=item.following__id %}">{{ item.following__username }}</a>
                                </td>
                                <td><p>{% if item.following__role == 1 %}Admin{% else %}Member{% endif %}</p>
                                </td>
                                <td>{{ item.total }}</td>
                            </tr>
                        {% endfor %}
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
    <div class="row">
        <div class="col-lg-6">
            <div class="card">
                <div class="card-header border-0">
                    <h3 class="card-title"><b>Top 5 most read member</b></h3>
                    <div class="card-tools">
                        <a href="#" class="btn btn-tool btn-sm">
                            <i class="fas fa-download"></i>
                        </a>
                        <a href="#" class="btn btn-tool btn-sm">
                            <i class="fas fa-bars"></i>
                        </a>
                    </div>
                </div>
                <div class="card-body table-responsive p-0">
                    <table class="table table-striped table-valign-middle">
                        <thead>
                        <tr>
                            <th>#</th>
                            <th>ID</th>
                            <th>Username</th>
                            <th>Role</th>
                            <th>Total (book)</th>
                        </tr>
                        </thead>
                        <tbody>
                        {% for item in most_read_book_members %}
                            <tr>
                                <td>{{ forloop.counter }}</td>
                                <td>{{ item.user__id }}</td>
                                <td>
                                    <a href="{% url 'users:user-detail' id=item.user__id %}">{{ item.user__username }}</a>
                                </td>
                                <td><p>{% if item.user__role == 1 %}Admin{% else %}Member{% endif %}</p>
                                </td>
                                <td>{{ item.total }}</td>
                            </tr>
                        {% endfor %}
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
        <div class="col-lg-6">
            <div class="card">
                <div class="card-header border-transparent">
                    <h3 class="card-title"><b>Latest login members</b></h3>

                    <div class="card-tools">
                        <button type="button" class="btn btn-tool" data-card-widget="collapse">
                            <i class="fas fa-minus"></i>
                        </button>
                        <button type="button" class="btn btn-tool" data-card-widget="remove">
                            <i class="fas fa-times"></i>
                        </button>
                    </div>
                </div>
                <!-- /.card-header -->
                <div class="card-body p-0">
                    <div class="table-responsive">
                        <table class="table m-0">
                            <thead>
                            <tr>
                                <th>#</th>
                                <th>ID</th>
                                <th>Username</th>
                                <th>Role</th>
                                <th>Last Login</th>
                            </tr>
                            </thead>
                            <tbody>
                            {% for item in users_login %}
                                <tr>
                                    <td>{{ forloop.counter }}</td>
                                    <td>{{ item.id }}</td>
                                    <td>
                                        <a href="{% url 'users:user-detail' id=item.id %}">{{ item.username }}</a>
                                    </td>
                                    <td><p>{% if item.role == 1 %}Admin{% else %}Member{% endif %}</p>
                                    </td>
                                    <td>{{ item.last_login }}</td>
                                </tr>
                            {% endfor %}
                            </tbody>
                        </table>
                    </div>
                    <!-- /.table-responsive -->
                </div>
                <!-- /.card-footer -->
            </div>
        </div>
    </div>
{% endblock %}

components/users/templates/signin.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>SignIn</title>
    <link rel="stylesheet" href="{% static 'css/adminlte.css' %}">
    <link rel="stylesheet" href="{% static 'plugins/fontawesome-free/css/all.min.css' %}">
</head>
<body class="login-page">
<div class="login-box">
    <div class="login-logo">
        <a href="#"><b>Sun Library</b></a>
    </div>
    <!-- /.login-logo -->
    <div class="card">
        <div class="card-body login-card-body">
            <p class="login-box-msg">Sign in to start your session</p>

            <form action="{% url 'users:signin' %}" method="post">
                {% if form.errors %}
                    {% for field in form %}
                        {% for error in field.errors %}
                            <div class="alert alert-danger">
                                <strong>{{ error|escape }}</strong>
                            </div>
                        {% endfor %}
                    {% endfor %}
                    {% for error in form.non_field_errors %}
                        <div class="alert alert-danger">
                            <strong>{{ error|escape }}</strong>
                        </div>
                    {% endfor %}
                {% endif %}
                {% csrf_token %}
                <div class="input-group mb-3">
                    <input type="email" class="form-control" placeholder="Email" name="email" required>
                    <div class="input-group-append">
                        <div class="input-group-text">
                            <span class="fas fa-envelope"></span>
                        </div>
                    </div>
                </div>
                <div class="input-group mb-3">
                    <input type="password" class="form-control" placeholder="Password" name="password" required>
                    <div class="input-group-append">
                        <div class="input-group-text">
                            <span class="fas fa-lock"></span>
                        </div>
                    </div>
                </div>
                <div class="row">
                    <div class="col-8">
                        <div class="icheck-primary">
                            <input type="checkbox" id="remember">
                            <label for="remember">
                                Remember Me
                            </label>
                        </div>
                    </div>
                    <!-- /.col -->
                    <div class="col-4">
                        <button type="submit" class="btn btn-primary btn-block">Sign In</button>
                    </div>
                    <!-- /.col -->
                </div>
            </form>

            <p class="mb-1">
                <a href="#">I forgot my password</a>
            </p>
            <p class="mb-0">
                <a href="{% url 'users:signup' %}" class="text-center">Register a new membership</a>
            </p>
        </div>
        <!-- /.login-card-body -->
    </div>
</div>
</body>
</html>